### Model Selection under different tsplib instances

The following table summarizes the performance of different models on various TSPLIB instances. Each model's effectiveness is evaluated based on the solution quality and computational time.

**Criteria**
- Runtime (seconds) : 60 percent
- Solution Quality (percentage of optimal) : 40 percent

**TSPlib instances**
- burma14
- bays29
- eil51
- berlin52

In [ ]:
%pip install tsplib95 numpy scikit-learn pandas

In [12]:
from Solver import Solver

##### Burma14

In [13]:
burma14 = Solver('burma14')
burma14.solve(10) # more iterations since it's a small instance

Loading TSP instance: burma14...
Best known cost: 3323
Starting TSP solving for 10 iterations...

Progress: 10% | Elapsed Time: 12.73s | ETA: 1.91 min
Progress: 20% | Elapsed Time: 12.04s | ETA: 1.61 min
Progress: 30% | Elapsed Time: 12.17s | ETA: 1.42 min
Progress: 40% | Elapsed Time: 12.08s | ETA: 1.21 min
Progress: 50% | Elapsed Time: 12.23s | ETA: 1.02 min
Progress: 60% | Elapsed Time: 12.16s | ETA: 0.81 min
Progress: 70% | Elapsed Time: 12.22s | ETA: 0.61 min
Progress: 80% | Elapsed Time: 11.62s | ETA: 0.39 min
Progress: 90% | Elapsed Time: 11.58s | ETA: 0.19 min
Progress: 100% | Elapsed Time: 11.25s | ETA: 0.00 min
All algorithms have been executed.

In [14]:
burma14.present_results()

         Avg Cost  Avg Runtime  Min Cost  Avg Rel Error  Min Rel Error
EHO        3323.0     0.172839    3323.0       0.000000       0.000000
SAI        3323.0     0.487624    3323.0       0.000000       0.000000
GA         3323.0     3.786792    3323.0       0.000000       0.000000
ACO        3340.6     2.513401    3336.0       0.529642       0.391213
PSO        3355.8     3.362830    3323.0       0.987060       0.000000
SA         3381.1     0.011975    3323.0       1.748420       0.000000
HSFFPKO    3385.5     1.160940    3323.0       1.880831       0.000000
GWO        3532.9     0.513078    3323.0       6.316581       0.000000

In [15]:
burma14.weighted_score(0.5)

            Score
EHO      0.021308
SAI      0.063003
SA       0.138399
HSFFPKO  0.301069
ACO      0.373255
GA       0.500000
PSO      0.521976
GWO      0.566374

#### Bays29

In [16]:
bays29 = Solver('bays29')
bays29.solve()

Loading TSP instance: bays29...
Best known cost: 2020
Starting TSP solving for 10 iterations...
Progress: 10% | Elapsed Time: 41.06s | ETA: 6.16 min
Progress: 20% | Elapsed Time: 40.57s | ETA: 5.41 min
Progress: 30% | Elapsed Time: 41.93s | ETA: 4.89 min
Progress: 40% | Elapsed Time: 46.44s | ETA: 4.64 min
Progress: 50% | Elapsed Time: 41.18s | ETA: 3.43 min
Progress: 60% | Elapsed Time: 47.09s | ETA: 3.14 min
Progress: 70% | Elapsed Time: 41.22s | ETA: 2.06 min
Progress: 80% | Elapsed Time: 39.57s | ETA: 1.32 min
Progress: 90% | Elapsed Time: 55.72s | ETA: 0.93 min
Progress: 100% | Elapsed Time: 50.42s | ETA: 0.00 min
All algorithms have been executed.

In [17]:
bays29.present_results()

         Avg Cost  Avg Runtime  Min Cost  Avg Rel Error  Min Rel Error
GA         2020.6    26.310887    2020.0       0.029703       0.000000
SAI        2028.4     1.044032    2020.0       0.415842       0.000000
ACO        2050.3     9.673584    2038.0       1.500000       0.891089
EHO        2094.9     0.268436    2020.0       3.707921       0.000000
PSO        2277.3     4.766637    2148.0      12.737624       6.336634
HSFFPKO    2427.7     1.424635    2226.0      20.183168      10.198020
GWO        2686.0     1.022335    2303.0      32.970297      14.009901
SA         2700.1     0.007750    2448.0      33.668317      21.188119

In [18]:
bays29.weighted_score(0.5)

            Score
SAI      0.025438
EHO      0.059628
ACO      0.205593
PSO      0.279351
HSFFPKO  0.326492
GA       0.500000
SA       0.500000
GWO      0.508911

#### Eil51

In [19]:
eils51 = Solver('eil51')
eils51.solve()

Loading TSP instance: eil51...
Best known cost: 426
Starting TSP solving for 10 iterations...
Progress: 10% | Elapsed Time: 214.34s | ETA: 32.15 min
Progress: 20% | Elapsed Time: 228.87s | ETA: 30.52 min
Progress: 30% | Elapsed Time: 189.71s | ETA: 22.13 min
Progress: 40% | Elapsed Time: 208.53s | ETA: 20.85 min
Progress: 50% | Elapsed Time: 211.36s | ETA: 17.61 min
Progress: 60% | Elapsed Time: 180.91s | ETA: 12.06 min
Progress: 70% | Elapsed Time: 192.73s | ETA: 9.64 min
Progress: 80% | Elapsed Time: 170.82s | ETA: 5.69 min
Progress: 90% | Elapsed Time: 252.92s | ETA: 4.22 min
Progress: 100% | Elapsed Time: 238.31s | ETA: 0.00 min
All algorithms have been executed.

In [20]:
eils51.present_results()

         Avg Cost  Avg Runtime  Min Cost  Avg Rel Error  Min Rel Error
GA          427.6   168.147386     426.0       0.375587       0.000000
SAI         437.8     1.819418     432.0       2.769953       1.408451
ACO         449.4    28.623852     443.0       5.492958       3.990610
EHO         513.2     0.441546     491.0      20.469484      15.258216
PSO         583.1     6.296093     556.0      36.877934      30.516432
HSFFPKO     968.2     1.783713     809.0     127.276995      89.906103
SA         1039.9     0.010353     925.0     144.107981     117.136150
GWO        1047.3     1.727914     789.0     145.845070      85.211268

In [21]:
eils51.weighted_score(0.5)

            Score
SAI      0.013610
EHO      0.070348
ACO      0.102679
PSO      0.144156
HSFFPKO  0.441452
SA       0.494029
GA       0.500000
GWO      0.505108

#### Berlin52

In [22]:
berlin52 = Solver('berlin52')
berlin52.solve()

Loading TSP instance: berlin52...
Best known cost: 7542
Starting TSP solving for 10 iterations...
Progress: 10% | Elapsed Time: 248.50s | ETA: 37.27 min
Progress: 20% | Elapsed Time: 245.63s | ETA: 32.75 min
Progress: 30% | Elapsed Time: 246.46s | ETA: 28.75 min
Progress: 40% | Elapsed Time: 238.34s | ETA: 23.83 min
Progress: 50% | Elapsed Time: 216.33s | ETA: 18.03 min
Progress: 60% | Elapsed Time: 206.43s | ETA: 13.76 min
Progress: 70% | Elapsed Time: 235.28s | ETA: 11.76 min
Progress: 80% | Elapsed Time: 249.37s | ETA: 8.31 min
Progress: 90% | Elapsed Time: 226.35s | ETA: 3.77 min
Progress: 100% | Elapsed Time: 272.60s | ETA: 0.00 min
All algorithms have been executed.

In [23]:
berlin52.present_results()

         Avg Cost  Avg Runtime  Min Cost  Avg Rel Error  Min Rel Error
GA         7542.0   196.586682    7542.0       0.000000       0.000000
ACO        7730.0    29.228995    7662.0       2.492708       1.591090
SAI        7779.4     1.902301    7542.0       3.147706       0.000000
EHO        9304.1     0.450361    8727.0      23.363829      15.712013
PSO       10820.0     6.839515    9883.0      43.463272      31.039512
SA        13805.1     0.011217   12745.0      83.042959      68.987006
HSFFPKO   16375.4     1.756992   14712.0     117.122779      95.067621
GWO       21220.1     1.752685   14840.0     181.359056      96.764784

In [24]:
berlin52.weighted_score(0.5)

            Score
SAI      0.013488
EHO      0.065530
ACO      0.081189
PSO      0.137195
SA       0.228946
HSFFPKO  0.327344
GA       0.500000
GWO      0.504430